[project]
name = "multimodal-game-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "typer>=0.15.2",
]

[project.scripts]
multimodal-game-agent = "multimodal_game_agent:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/owa_game_agent"]
